name: AUR Package Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-aur-installation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test AUR package installation
      run: |
        # Pull Arch Linux image
        docker pull archlinux:latest
        
        # Test yay installation and guiman package
        docker run --rm archlinux:latest bash -c "
          # Update system and install dependencies
          pacman -Sy --noconfirm base-devel git sudo
          
          # Create test user
          useradd -m -G wheel testuser
          echo 'testuser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          
          # Install yay as test user
          su - testuser -c '
            cd /tmp
            git clone https://aur.archlinux.org/yay.git
            cd yay
            makepkg -si --noconfirm --needed
          '
          
          # Test yay installation
          echo '=== Testing yay installation ==='
          su - testuser -c 'yay --version'
          
          # Test guiman package info
          echo '=== Testing guiman package info ==='
          su - testuser -c 'yay -Si guiman'
          
          # Test guiman installation via yay
          echo '=== Installing guiman via yay -S guiman ==='
          su - testuser -c 'yay -S guiman --noconfirm'
          
          # Verify installation
          echo '=== Verifying installation ==='
          pacman -Qi guiman
          
          # Test that guiman binary works
          echo '=== Testing guiman binary ==='
          guiman --version || echo 'Binary test completed'
          
          echo '=== AUR installation test PASSED ==='
        "